version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: vhm/react-dockerize
    container_name: react-dockerize
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: vhm/react-dockerize
    container_name: react-dockerfile-tests
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]


